=== ibq-daw1-1920-17/lmsgi/Unidad_04/Unidad_04_Actividad_03/Actividad_03_05.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="presentacion"></xs:element>
    <xs:element name="datos_academicos"></xs:element>
    <xs:element name="experiencia_laboral"></xs:element>
    <xs:element name="lectura"></xs:element>
    <xs:element name="deporte"></xs:element>
    <xs:element name="otros"></xs:element>
    <xs:element name="referencias"></xs:element>
    <xs:attribute name="nacionalidad"></xs:attribute>

    <xs:element name="cv">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="presentacion"></xs:element>
                <xs:element ref="datos_academicos" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element ref="experiencia_laboral" minOccurs="1" maxOccurs="unbounded"></xs:element>
                <xs:element ref="lectura" minOccurs="0" maxOccurs="unbounded"></xs:element>
                <xs:element ref="deporte" minOccurs="0" maxOccurs="unbounded"></xs:element>
                <xs:element ref="otros" minOccurs="0" maxOccurs="unbounded"></xs:element>
                <xs:element ref="referencias" minOccurs="0" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
            <xs:attribute ref="nacionalidad"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ibq-daw1-1920-17/lmsgi/Unidad_04/Unidad_04_Actividad_03/Actividad_03_05.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="Actividad_03_05.xsd">

<!--ELEMENT cv (presentacion, datos_academicos+, experiencia_laboral+, lectura*, deportes*, otros*, referencias*)-->

  <presentacion>Curriculum vitae de Juan Mu√±iz</presentacion>
  <datos_academicos>Titulo de bachiller</datos_academicos>
  <experiencia_laboral>camarero</experiencia_laboral>
  <experiencia_laboral>comercial</experiencia_laboral>
  <experiencia_laboral>vigilante de seguridad</experiencia_laboral>
  <lectura>La biblia</lectura>
  <referencias> Llagar el Titi</referencias>
  <referencias> Prosegur</referencias>
</cv>
