=== ibq-daw1-1920-17/lmsgi/Unidad_04/Unidad_04_Actividad_03/Actividad_03_10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Nombre"></xs:element>
    <xs:element name="Direccion"></xs:element>
    <xs:element name="Ciudad"></xs:element>
    <xs:element name="CodPostal"></xs:element>
    <xs:element name="descripcion"></xs:element>
    <xs:element name="precio"></xs:element>
    <xs:element name="cantidad"></xs:element>
    <xs:element name="Observaciones"></xs:element>

    <xs:attribute name="codigo" type="xs:string"></xs:attribute>
    <xs:attribute name="fecha" type="xs:date"></xs:attribute>

    <xs:element name="Producto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="descripcion"></xs:element>
                <xs:element ref="precio"></xs:element>
                <xs:element ref="cantidad"></xs:element>
            </xs:sequence>
            <xs:attribute ref="codigo"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Contenido">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Producto" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Destino">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nombre"></xs:element>
                <xs:element ref="Direccion"></xs:element>
                <xs:element ref="Ciudad"></xs:element>
                <xs:element ref="CodPostal"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Ordenante">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Nombre"></xs:element>
                <xs:element ref="Direccion"></xs:element>
                <xs:element ref="Ciudad"></xs:element>
                <xs:element ref="CodPostal"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Destino"></xs:element>
                <xs:element ref="Ordenante"></xs:element>
                <xs:element ref="Observaciones"></xs:element>
                <xs:element ref="Contenido"></xs:element>
            </xs:sequence>
            <xs:attribute ref="fecha"></xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ibq-daw1-1920-17/lmsgi/Unidad_04/Unidad_04_Actividad_03/Actividad_03_10.xml
<?xml version="1.0" encoding="UTF-8"?>

<Pedido fecha="1999-10-21" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation= "Actividad_03_10.xsd">
      <Destino>
          <Nombre>Alicia Abad</Nombre>
          <Direccion>Plaza de la Duquesa 12,</Direccion>
          <Ciudad>Albacete</Ciudad>
          <CodPostal>05020</CodPostal>
      </Destino>
      <Ordenante>
          <Nombre>Roberto Movilla,</Nombre>
          <Direccion>General Ricardos 56,</Direccion>
          <Ciudad>Madrid</Ciudad>
          <CodPostal>28055</CodPostal>
      </Ordenante>
      <Observaciones>Cortadora cesped Â¿electrica?</Observaciones>
      <Contenido>
          <Producto codigo="872-AA">
              <descripcion>Cortadora de cesped</descripcion>
              <precio>148.95</precio>
	            <cantidad>1</cantidad>
          </Producto>
          <Producto codigo="926-FH">
              <descripcion>Podadora setos</descripcion>
              <precio>7.98</precio>
	            <cantidad>3</cantidad>
           </Producto>
          
      </Contenido>
</Pedido>
