<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (partido)+>
<!ELEMENT partido (equipoVisitante, equipoLocal)>
<!ELEMENT equipoVisitante (#PCDATA)>
<!ELEMENT equipoLocal (#PCDATA)>
<!ATTLIST equipoLocal goles CDATA #REQUIRED>
<!ATTLIST equipoVisitante goles CDATA #REQUIRED>

]>

<resultados>
    <partido>
        <equipoVisitante goles="0">Nottingham Presa</equipoVisitante>
        <equipoLocal goles="1">Inter de Mitente</equipoLocal>
    </partido>
    <partido>
        <equipoVisitante goles="3">Vodka Juniors</equipoVisitante>
        <equipoLocal goles="3">Sparta da Risa</equipoLocal>
    </partido>
    <partido>
        <equipoVisitante goles="4">Water de Munich</equipoVisitante>
        <equipoLocal goles="2">Esteaua es del grifo</equipoLocal>
    </partido>
</resultados>